#!/usr/bin/env python3
import argparse as ap
import os
import os.path
import shutil

def cpfiles(args):
    topdir = args['from']
    dstdir = args['outputdir']
    ext = args['extension']
    for dirpath, dirnames, filenames in os.walk(topdir):
        for filename in [f for f in filenames if f.endswith(ext)]:
            print("Now copying %s", filename)
            shutil.copy(os.path.join(dirpath, filename), dstdir)

parser = ap.ArgumentParser()
parser.add_argument('-F', '--from', type=str, help='The directory where files located including subdirectories')
parser.add_argument('-O', '--outputdir', type=str, help='The directory where files copy to')
parser.add_argument('-E', '--extension', type=str, help="extension of files to copy")

if __name__ == '__main__':
    args = vars(parser.parse_args())
    cpfiles(args)

